application: vertix
api_version: 1
version: 1
runtime: python27
threadsafe: True

handlers:
# - url: /static/
#   static_dir: static/bs-admin

# - url: /index\.html
#   static_files: templates/index.html
#   upload: templates/index.html

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/sb-admin/\1
  upload: static/bs-admin/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/sb-admin/\1
  upload: static/bs-admin/(.*\.js)

- url: /doc
  static_dir: doc/build/html

- url: /_ah/spi/.*
  script: main_api.vertix_application

- url: .*
  script: main.vertix_application

libraries:
 - name: webapp2
   version: latest

 - name: webob
   version: latest

 - name: endpoints
   version: latest
