application: vetrix
api_version: 1
version: 1
runtime: python27
threadsafe: True

handlers:
- url: /templates
  static_dir: templates

- url: /index\.html
  static_files: templates/index.html
  upload: templates/index.html

- url: /doc
  static_dir: doc/build/html

- url: /_ah/spi/.*
  script: main_api.vertix_application

- url: .*
  script: main.vertix_application

libraries:
 - name: webapp2
   version: latest

 - name: webob
   version: latest

 - name: endpoints
   version: latest